/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    projects: Project;
    'timeline-items': TimelineItem;
    certifications: Certification;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'timeline-items': TimelineItemsSelect<false> | TimelineItemsSelect<true>;
    certifications: CertificationsSelect<false> | CertificationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-meta': SiteMeta;
    about: About;
  };
  globalsSelect: {
    'site-meta': SiteMetaSelect<false> | SiteMetaSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Bibliothèque centrale de tous les fichiers uploadés (images des projets, photo, CV PDF). Tout fichier ajouté ici devient sélectionnable depuis les champs « upload » des autres collections (En-tête de projet, image dans un write-up, photo de l'À propos, CV des métadonnées, etc.). La liste est vide tant que tu n'as rien uploadé.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Description courte pour l'accessibilité.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * Auto-généré depuis le titre si laissé vide (kebab-case sans accents).
   */
  slug?: string | null;
  /**
   * Ex : « monitoring · devsecops ».
   */
  category: string;
  /**
   * Résumé court (240 caractères max) affiché sur les cartes.
   */
  description: string;
  /**
   * Badges techno affichés sur la fiche projet.
   */
  stack: {
    value: string;
    id?: string | null;
  }[];
  /**
   * URL complète (https://...) — optionnel.
   */
  github?: string | null;
  /**
   * Ex : « 2024 - en cours ».
   */
  period: string;
  /**
   * Ex : « Projet personnel », « Mission », etc.
   */
  type: string;
  /**
   * Étiquette optionnelle (« en cours », « archivé », ...).
   */
  badge?: string | null;
  /**
   * Plus petit = affiché en premier.
   */
  order: number;
  /**
   * Assemble la page bloc par bloc. Si tu n'ajoutes aucun bloc structurel (en-tête, méta, tags, nav), un layout par défaut est appliqué automatiquement.
   */
  content?:
    | (
        | {
            showBackLink?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'project-header';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'project-meta';
          }
        | {
            /**
             * Rendu en mono uppercase préfixé `//` dans la couleur d'accent.
             */
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'section-heading';
          }
        | {
            /**
             * Texte courant. Le gras (`<strong>`) est rendu en accent neutre fort.
             */
            text: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'paragraph';
          }
        | {
            language: 'bash' | 'ts' | 'tsx' | 'go' | 'yaml' | 'dockerfile' | 'sh' | 'json' | 'python';
            /**
             * Optionnel — affiché en en-tête du bloc.
             */
            filename?: string | null;
            /**
             * Contenu brut — pas d'interprétation Markdown.
             */
            code: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'code-block';
          }
        | {
            /**
             * Bloc d'emphase rendu avec le composant Highlight (bordure colorée).
             */
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'highlight';
          }
        | {
            /**
             * Payload JSON consommé par le composant ArchitectureDiagram (noeuds, liens, légende).
             */
            data:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'architecture-diagram';
          }
        | {
            image: number | Media;
            /**
             * Optionnelle — affichée sous l'image en mono petite taille.
             */
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'project-tags';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'project-nav';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline-items".
 */
export interface TimelineItem {
  id: number;
  /**
   * Ex : « fév. 2023 - fév. 2024 ».
   */
  date: string;
  title: string;
  subtitle: string;
  /**
   * Si rempli, l'item est marqué comme actif (point plein sur la timeline) et le texte est affiché sous le sous-titre. Laisse vide pour un item passé.
   */
  activeLabel?: string | null;
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications".
 */
export interface Certification {
  id: number;
  name: string;
  organization: string;
  status: 'obtained' | 'in-progress' | 'course-only';
  /**
   * Texte affiché sur le badge (ex : « 2024 », « en préparation »).
   */
  statusLabel: string;
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'timeline-items';
        value: number | TimelineItem;
      } | null)
    | ({
        relationTo: 'certifications';
        value: number | Certification;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  description?: T;
  stack?:
    | T
    | {
        value?: T;
        id?: T;
      };
  github?: T;
  period?: T;
  type?: T;
  badge?: T;
  order?: T;
  content?:
    | T
    | {
        'project-header'?:
          | T
          | {
              showBackLink?: T;
              id?: T;
              blockName?: T;
            };
        'project-meta'?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        'section-heading'?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        paragraph?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        'code-block'?:
          | T
          | {
              language?: T;
              filename?: T;
              code?: T;
              id?: T;
              blockName?: T;
            };
        highlight?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        'architecture-diagram'?:
          | T
          | {
              data?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        'project-tags'?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        'project-nav'?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline-items_select".
 */
export interface TimelineItemsSelect<T extends boolean = true> {
  date?: T;
  title?: T;
  subtitle?: T;
  activeLabel?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications_select".
 */
export interface CertificationsSelect<T extends boolean = true> {
  name?: T;
  organization?: T;
  status?: T;
  statusLabel?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-meta".
 */
export interface SiteMeta {
  id: number;
  name?: string | null;
  title?: string | null;
  description?: string | null;
  email?: string | null;
  /**
   * URL complète du profil.
   */
  github?: string | null;
  /**
   * URL complète du profil.
   */
  linkedin?: string | null;
  location?: string | null;
  availability?: string | null;
  /**
   * Optionnel — si vide, le bouton CV n'est pas affiché sur le site.
   */
  cv?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  /**
   * Optionnelle — si vide, la photo n'est pas affichée sur le site.
   */
  photo?: (number | null) | Media;
  quickInfo?: {
    location?: string | null;
    rhythm?: string | null;
    english?: string | null;
  };
  sectionTitle?: string | null;
  /**
   * Ajoute, retire, réordonne librement des paragraphes et des encarts.
   */
  content?:
    | (
        | {
            /**
             * Texte courant. Le gras (`<strong>`) est rendu en accent neutre fort.
             */
            text: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'paragraph';
          }
        | {
            /**
             * Bloc d'emphase rendu avec le composant Highlight (bordure colorée).
             */
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'highlight';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-meta_select".
 */
export interface SiteMetaSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  description?: T;
  email?: T;
  github?: T;
  linkedin?: T;
  location?: T;
  availability?: T;
  cv?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  photo?: T;
  quickInfo?:
    | T
    | {
        location?: T;
        rhythm?: T;
        english?: T;
      };
  sectionTitle?: T;
  content?:
    | T
    | {
        paragraph?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        highlight?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}