/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    projects: Project;
    posts: Post;
    'timeline-items': TimelineItem;
    certifications: Certification;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'timeline-items': TimelineItemsSelect<false> | TimelineItemsSelect<true>;
    certifications: CertificationsSelect<false> | CertificationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-meta': SiteMeta;
    about: About;
  };
  globalsSelect: {
    'site-meta': SiteMetaSelect<false> | SiteMetaSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Images des Notes, photo de profil et CV PDF. Un fichier ajouté ici devient sélectionnable depuis les champs média du site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Description courte pour l'accessibilité.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Un thème sert uniquement à filtrer et regrouper des Notes. Il ne possède pas de page publique ni de contenu propre.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * Auto-généré depuis le nom si laissé vide.
   */
  slug?: string | null;
  /**
   * Plus petit = affiché en premier.
   */
  order: number;
  shortTitle?: string | null;
  category: string;
  kind: 'living-system' | 'product' | 'case-study' | 'experiment';
  cardVisual: 'auto' | 'homelab' | 'crisis' | 'phantom' | 'system';
  cover?: (number | null) | Media;
  description: string;
  stack: {
    value: string;
    id?: string | null;
  }[];
  github?: string | null;
  period: string;
  type: string;
  badge?: string | null;
  featured?: boolean | null;
  listedInNotes?: boolean | null;
  publishedAt?: string | null;
  readingTime?: number | null;
  parentProject?: (number | null) | Project;
  relatedProjects?: (number | Project)[] | null;
  /**
   * Archive conservée pour rollback après migration du contenu vers Notes.
   */
  content?:
    | (
        | {
            showBackLink?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'project-header';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'project-meta';
          }
        | {
            /**
             * Titre éditorial sobre, sans préfixe décoratif.
             */
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'section-heading';
          }
        | {
            /**
             * Texte courant. Le gras (`<strong>`) est rendu en accent neutre fort.
             */
            text: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'paragraph';
          }
        | {
            language: 'bash' | 'ts' | 'tsx' | 'go' | 'yaml' | 'dockerfile' | 'sh' | 'json' | 'python';
            /**
             * Optionnel — affiché en en-tête du bloc.
             */
            filename?: string | null;
            /**
             * Contenu brut — pas d'interprétation Markdown.
             */
            code: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'code-block';
          }
        | {
            /**
             * Bloc d'emphase rendu avec le composant Highlight (bordure colorée).
             */
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'highlight';
          }
        | {
            caption?: string | null;
            columns: {
              label: string;
              align: 'left' | 'center' | 'right';
              id?: string | null;
            }[];
            rows: {
              cells: {
                value: string;
                tone: 'default' | 'positive' | 'warning';
                id?: string | null;
              }[];
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'table';
          }
        | {
            title?: string | null;
            nodes?:
              | {
                  /**
                   * Ex : vps, homelab, observabilite.
                   */
                  key: string;
                  label: string;
                  detail?: string | null;
                  tone?: ('default' | 'mauve' | 'orange') | null;
                  id?: string | null;
                }[]
              | null;
            links?:
              | {
                  from: string;
                  to: string;
                  label?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Compatibilité avec les schémas créés avant les champs structurés.
             */
            data?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'architecture-diagram';
          }
        | {
            image: number | Media;
            /**
             * Optionnelle — affichée sous l'image en mono petite taille.
             */
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'project-tags';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'project-nav';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Tout le contenu public se publie ici. Une Note est indépendante par défaut ; un thème sert seulement à regrouper plusieurs Notes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Auto-généré depuis le titre si laissé vide.
   */
  slug?: string | null;
  excerpt: string;
  publishedAt: string;
  readingTime: number;
  cover?: (number | null) | Media;
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Facultatif : laisse vide pour une Note indépendante. Un thème comme Homelab sert uniquement de filtre et de regroupement.
   */
  relatedProjects?: (number | Project)[] | null;
  /**
   * Blocs bornés et réutilisables. Le code reste du texte brut ; tableaux et schémas sont validés avant enregistrement.
   */
  content: (
    | {
        /**
         * Titre éditorial sobre, sans préfixe décoratif.
         */
        text: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'section-heading';
      }
    | {
        /**
         * Texte courant. Le gras (`<strong>`) est rendu en accent neutre fort.
         */
        text: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'paragraph';
      }
    | {
        language: 'bash' | 'ts' | 'tsx' | 'go' | 'yaml' | 'dockerfile' | 'sh' | 'json' | 'python';
        /**
         * Optionnel — affiché en en-tête du bloc.
         */
        filename?: string | null;
        /**
         * Contenu brut — pas d'interprétation Markdown.
         */
        code: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'code-block';
      }
    | {
        /**
         * Bloc d'emphase rendu avec le composant Highlight (bordure colorée).
         */
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'highlight';
      }
    | {
        caption?: string | null;
        columns: {
          label: string;
          align: 'left' | 'center' | 'right';
          id?: string | null;
        }[];
        rows: {
          cells: {
            value: string;
            tone: 'default' | 'positive' | 'warning';
            id?: string | null;
          }[];
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'table';
      }
    | {
        title?: string | null;
        nodes?:
          | {
              /**
               * Ex : vps, homelab, observabilite.
               */
              key: string;
              label: string;
              detail?: string | null;
              tone?: ('default' | 'mauve' | 'orange') | null;
              id?: string | null;
            }[]
          | null;
        links?:
          | {
              from: string;
              to: string;
              label?: string | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Compatibilité avec les schémas créés avant les champs structurés.
         */
        data?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        caption?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'architecture-diagram';
      }
    | {
        image: number | Media;
        /**
         * Optionnelle — affichée sous l'image en mono petite taille.
         */
        caption?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'image';
      }
  )[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline-items".
 */
export interface TimelineItem {
  id: number;
  /**
   * Ex : « fév. 2023 - fév. 2024 ».
   */
  date: string;
  title: string;
  subtitle: string;
  /**
   * Si rempli, l'item est marqué comme actif (point plein sur la timeline) et le texte est affiché sous le sous-titre. Laisse vide pour un item passé.
   */
  activeLabel?: string | null;
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications".
 */
export interface Certification {
  id: number;
  name: string;
  organization: string;
  status: 'obtained' | 'in-progress' | 'course-only';
  /**
   * Texte affiché sur le badge (ex : « 2024 », « en préparation »).
   */
  statusLabel: string;
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'timeline-items';
        value: number | TimelineItem;
      } | null)
    | ({
        relationTo: 'certifications';
        value: number | Certification;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  order?: T;
  shortTitle?: T;
  category?: T;
  kind?: T;
  cardVisual?: T;
  cover?: T;
  description?: T;
  stack?:
    | T
    | {
        value?: T;
        id?: T;
      };
  github?: T;
  period?: T;
  type?: T;
  badge?: T;
  featured?: T;
  listedInNotes?: T;
  publishedAt?: T;
  readingTime?: T;
  parentProject?: T;
  relatedProjects?: T;
  content?:
    | T
    | {
        'project-header'?:
          | T
          | {
              showBackLink?: T;
              id?: T;
              blockName?: T;
            };
        'project-meta'?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        'section-heading'?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        paragraph?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        'code-block'?:
          | T
          | {
              language?: T;
              filename?: T;
              code?: T;
              id?: T;
              blockName?: T;
            };
        highlight?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        table?:
          | T
          | {
              caption?: T;
              columns?:
                | T
                | {
                    label?: T;
                    align?: T;
                    id?: T;
                  };
              rows?:
                | T
                | {
                    cells?:
                      | T
                      | {
                          value?: T;
                          tone?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'architecture-diagram'?:
          | T
          | {
              title?: T;
              nodes?:
                | T
                | {
                    key?: T;
                    label?: T;
                    detail?: T;
                    tone?: T;
                    id?: T;
                  };
              links?:
                | T
                | {
                    from?: T;
                    to?: T;
                    label?: T;
                    id?: T;
                  };
              data?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        'project-tags'?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        'project-nav'?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  publishedAt?: T;
  readingTime?: T;
  cover?: T;
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  relatedProjects?: T;
  content?:
    | T
    | {
        'section-heading'?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        paragraph?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        'code-block'?:
          | T
          | {
              language?: T;
              filename?: T;
              code?: T;
              id?: T;
              blockName?: T;
            };
        highlight?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        table?:
          | T
          | {
              caption?: T;
              columns?:
                | T
                | {
                    label?: T;
                    align?: T;
                    id?: T;
                  };
              rows?:
                | T
                | {
                    cells?:
                      | T
                      | {
                          value?: T;
                          tone?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'architecture-diagram'?:
          | T
          | {
              title?: T;
              nodes?:
                | T
                | {
                    key?: T;
                    label?: T;
                    detail?: T;
                    tone?: T;
                    id?: T;
                  };
              links?:
                | T
                | {
                    from?: T;
                    to?: T;
                    label?: T;
                    id?: T;
                  };
              data?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline-items_select".
 */
export interface TimelineItemsSelect<T extends boolean = true> {
  date?: T;
  title?: T;
  subtitle?: T;
  activeLabel?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications_select".
 */
export interface CertificationsSelect<T extends boolean = true> {
  name?: T;
  organization?: T;
  status?: T;
  statusLabel?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Nom, manifeste de l'accueil, liens de contact et CV public.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-meta".
 */
export interface SiteMeta {
  id: number;
  contentRevision?: number | null;
  name?: string | null;
  email?: string | null;
  /**
   * URL complète du profil.
   */
  github?: string | null;
  /**
   * URL complète du profil.
   */
  linkedin?: string | null;
  hero?: {
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
  };
  /**
   * Optionnel — si vide, le bouton CV n'est pas affiché sur le site.
   */
  cv?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Présentation durable, localisation publique et récit affiché avant le parcours.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  /**
   * Optionnelle et remplaçable. Un monogramme est affiché si elle est absente.
   */
  photo?: (number | null) | Media;
  /**
   * Présentation durable : expertise, façon de travailler et sujets construits.
   */
  intro?: string | null;
  specialties?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  quickInfo?: {
    /**
     * Reste volontairement approximatif et modifiable.
     */
    location?: string | null;
    /**
     * Optionnel. Ne renseigne ni adresse précise ni déplacement incertain.
     */
    mobility?: string | null;
    english?: string | null;
  };
  sectionTitle?: string | null;
  /**
   * Ajoute, retire et réordonne les paragraphes. Cette zone n'est pas le CV.
   */
  content?:
    | (
        | {
            /**
             * Texte courant. Le gras (`<strong>`) est rendu en accent neutre fort.
             */
            text: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'paragraph';
          }
        | {
            /**
             * Bloc d'emphase rendu avec le composant Highlight (bordure colorée).
             */
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'highlight';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-meta_select".
 */
export interface SiteMetaSelect<T extends boolean = true> {
  contentRevision?: T;
  name?: T;
  email?: T;
  github?: T;
  linkedin?: T;
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  cv?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  photo?: T;
  intro?: T;
  specialties?:
    | T
    | {
        value?: T;
        id?: T;
      };
  quickInfo?:
    | T
    | {
        location?: T;
        mobility?: T;
        english?: T;
      };
  sectionTitle?: T;
  content?:
    | T
    | {
        paragraph?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        highlight?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}